version: '3'
services:
  db:
    image: postgres
    container_name: person-postgres
    environment:
      - POSTGRES_USER=person
      - POSTGRES_PASSWORD=person
      - POSTGRES_DB=person
    ports:
      - "5432:5432"
    #   Set a volume some that database is not lost after shutting down the container.
      #    volumes:
      #     - ./postgres-data:/var/lib/postgresql/data